// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { RxHamburgerMenu } from 'react-icons/rx';
import HeaderPanel from '@/components/HeaderPanel';
import Menu from '@/components/Menu';
import { MdOutlineKeyboardArrowDown } from 'react-icons/md';
import { MdOutlineKeyboardArrowUp } from 'react-icons/md';
// const geistSans = Geist({
//    variable: '--font-geist-sans',
//    subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//    variable: '--font-geist-mono',
//    subsets: ['latin'],
// });

// export const metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <head>
            <meta name="application-name" content="workersgen" />
            <meta name="apple-mobile-web-app-capable" content="yes" />
            <meta
               name="apple-mobile-web-app-status-bar-style"
               content="default"
            />
            <meta name="apple-mobile-web-app-title" content="workersgen" />
            <meta name="description" content="A crm software platform" />
            <meta name="format-detection" content="telephone=no" />
            <meta name="mobile-web-app-capable" content="yes" />
            <meta
               name="msapplication-config"
               content="/icons/browserconfig.xml"
            />
            <meta name="msapplication-TileColor" content="#ffff" />
            <meta name="msapplication-tap-highlight" content="no" />
            <meta name="theme-color" content="#ffff" />
            <meta name="background-color" content="#000000" />

            <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
            <link
               rel="apple-touch-icon"
               sizes="152x152"
               href="/icon-152x152.png"
            />
            <link
               rel="apple-touch-icon"
               sizes="180x180"
               href="/icon-180x180.png"
            />
            <link
               rel="apple-touch-icon"
               sizes="167x167"
               href="/icon-167x167.png"
            />

            <link
               rel="icon"
               type="image/png"
               sizes="32x32"
               href="/favicon-32x32.png"
            />
            <link
               rel="icon"
               type="image/png"
               sizes="16x16"
               href="/favicon-16x16.png"
            />
            <link rel="manifest" href="/manifest.json" />
            <link rel="shortcut icon" href="/favicon.ico" />

            <meta name="twitter:card" content="summary" />
            {/* <meta name="twitter:url" content="https://yourdomain.com" /> */}
            <meta name="twitter:title" content="crm" />
            <meta
               name="twitter:description"
               content="A crm software platform"
            />

            <meta name="twitter:creator" content="@paulinusmfon" />
            <meta property="og:type" content="website" />
            <meta property="og:title" content="crm workersgen" />
            <meta property="og:description" content="A crm software platform" />
            <meta property="og:site_name" content="Crm" />

            <meta
               name="viewport"
               content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover"
            />
         </head>
         <body className="flex min-h-screen">
            <div className="relative bg-[#efefef] py-2 border-r border-2 w-[14%] md:w-[8%] lg:w-[18%] xl:w-[14%] ">
               <div className="px-2 ">
                  <RxHamburgerMenu size={20} className="text-black lg:ml-2 " />
                  <Menu />
               </div>
               <div className="absolute bottom-0 w-full border-t-2 flex items-center pt-2 gap-2 border-gray-400">
                  <span className="bg-[#6c5689] py-2 lg:px-4  px-3 rounded-sm">
                     s
                  </span>
                  <span className=" lg:mr-auto hidden lg:block text-[#939393]">
                     Sales
                  </span>
                  <span>
                     <MdOutlineKeyboardArrowUp
                        size={16}
                        className="text-[#939393]"
                     />
                     <MdOutlineKeyboardArrowDown
                        size={16}
                        className="text-[#939393]"
                     />
                  </span>
               </div>
            </div>
            <div className="bg-white w-[86%] md:w-[92%] py-4 px-3  lg:w-[82%] xl:w-[86%]">
               <HeaderPanel />
               {children}
            </div>
         </body>
      </html>
   );
}
