export const people = [
   {
      id: 1,
      name: 'John Doe',
      created_on: '1995-05-24',
      topic: 'Web Developer',
      status: 'New',
   },
   {
      id: 2,
      name: 'Jane Doe',
      created_on: '1980-11-04',
      topic: 'Web Designer',
      status: 'New',
   },
   {
      id: 3,
      name: 'Gary Barlow',
      created_on: '1982-01-20',
      topic: 'Singer',
      status: 'New',
   },
   {
      id: 4,
      name: 'Sarah Connor',
      created_on: '1990-06-15',
      topic: 'Marketing Manager',
      status: 'New',
   },
   {
      id: 5,
      name: 'Michael Scott',
      created_on: '1975-03-15',
      topic: 'Regional Manager',
      status: 'New',
   },
   {
      id: 6,
      name: 'Dwight Schrute',
      created_on: '1978-01-20',
      topic: 'Assistant to the Regional Manager',
      status: 'New',
   },
   {
      id: 7,
      name: 'Pam Beesly',
      created_on: '1983-08-25',
      topic: 'Receptionist',
      status: 'New',
   },
   {
      id: 8,
      name: 'Jim Halpert',
      created_on: '1985-10-10',
      topic: 'Sales Representative',
      status: 'New',
   },
   {
      id: 9,
      name: 'Kelly Kapoor',
      created_on: '1984-12-05',
      topic: 'Customer Service Rep',
      status: 'New',
   },
   {
      id: 10,
      name: 'Andy Bernard',
      created_on: '1977-09-17',
      topic: 'Sales Manager',
      status: 'New',
   },
];
